export interface Puzzle {
  level: number
  question: string
  description: string
  imageUrl: string
  solution: string
  category: string
  hints: string[]
  isPuzzleImage?: boolean
  isInteractiveInmates?: boolean
  isLibraryPuzzle?: boolean
  isParrotPuzzle?: boolean
  isCoffeeGroundsPuzzle?: boolean
  isQuestionnairePuzzle?: boolean
  isCrystalJigsawPuzzle?: boolean
  isCrocodileJigsawPuzzle?: boolean
  isJigsawPuzzle?: boolean
  isZodiacPuzzle?: boolean
  isTarotPuzzle?: boolean
  isAnimatedGifPuzzle?: boolean
  isFamiliarFacesPuzzle?: boolean
  isHellJigsawPuzzle?: boolean
  isFinalJigsawPuzzle?: boolean
  isLightSwitchPuzzle?: boolean
  isFinalLevelPuzzle?: boolean
  isInfernalCasinoPuzzle?: boolean
  isEgyptianPillarsPuzzle?: boolean
  isPyramidPuzzle?: boolean
  isEgyptianMathPuzzle?: boolean
  isDarkRoomPuzzle?: boolean
  isMouthOfTruth?: boolean
  isBinarySwitchPuzzle?: boolean
  isFireMapPuzzle?: boolean
  isGoldenScarabPuzzle?: boolean
  inmateData?: any[]
  guardStatement?: string
}
