export interface Puzzle {
  id: number
  level: number
  title: string
  description: string
  hint: string
  answer: string
  character: string
  location: string
  background: string
  isInmatePuzzle?: boolean
  isLibraryPuzzle?: boolean
  isTarotPuzzle?: boolean
  isAnimatedGifPuzzle?: boolean
  isZodiacPuzzle?: boolean
  isParrotPuzzle?: boolean
  isCoffeeGroundsPuzzle?: boolean
  isQuestionnairePuzzle?: boolean
  isCrystalJigsawPuzzle?: boolean
  isCrocodileJigsawPuzzle?: boolean
  isHellJigsawPuzzle?: boolean
  isFamiliarFacesPuzzle?: boolean
  isJigsawPuzzle?: boolean
  isCrystalSequencePuzzle?: boolean
  isDevilDialogue?: boolean
  isElevatorPanel?: boolean
  isFinalJigsawPuzzle?: boolean
  isLightSwitchPuzzle?: boolean
  isFinalLevelPuzzle?: boolean
  isInfernalCasinoPuzzle?: boolean
  isEgyptianPillarsPuzzle?: boolean
  isPyramidPuzzle?: boolean
  isMouthOfTruthPuzzle?: boolean
  isBinarySwitchPuzzle?: boolean
  isEgyptianMathPuzzle?: boolean
  isDarkRoomPuzzle?: boolean
  isColorPalettePuzzle?: boolean
  isMurderMysteryPuzzle?: boolean
  isGoldenScarabPuzzle?: boolean
  isPyramidOfHanoiPuzzle?: boolean
  isFireMapPuzzle?: boolean
  isMagicBoxPuzzle?: boolean
  isAnswerInput?: boolean
}
